import type { Metadata } from 'next'
import './globals.css'
import { berkeleyMono } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${berkeleyMono.variable} font-mono antialiased h-screen w-screen`}
      >
        <div className='p-4 mx-auto max-w-screen-lg'>{children}</div>
      </body>
    </html>
  )
}
